### ISSUE TITLE
Two tests for the same thing?

### ISSUE THREAD

**Issue by drhollings** [summerwind/h2spec#52]
The test case from 5.1: "half closed (remote): Sends a DATA frame" appears to be testing the same path as the test case from 6.1: "Sends a DATA frame on the stream that is not opened". Perhaps one should be deleted or the test cases disambiguated more clearly? The 6.1 test in particular is somewhat confusing since "not opened" could mean a few different states.

**Comment by summerwind** [comment]
Thank you the feedback!

As you say, this test is duplicated. Since the test cases of h2spec have been created based on the RFC, if the description in RFC is duplicated, the test cases of h2spec is also duplicate.

However, the term "is not opend" will lead to confusion. So I'm going to change the description of the test case.

**Comment by summerwind** [comment]
The description was fixed in 5f374d94ec81f4f7a59cd875c60cebe220ef6abc.
